name: Build
on:
  push:
    branches: [main]
  pull_request:

jobs:
  qodana:
    name: Qodana check
    runs-on: ubuntu-latest
    steps:
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2022.3.4