name: Build
on:
  push:
    branches: [main]
  pull_request:

jobs:
  runPluginVerifier:
    name: Run Plugin Verifier
    runs-on: ubuntu-latest
    steps:
      - name: Setup Plugin Verifier IDEs Cache # Cache Plugin Verifier IDEs
        uses: actions/cache@v3
        with:
          path: ${{ steps.properties.outputs.pluginVerifierHomeDir }}/ides
          key: plugin-verifier-${{ hashFiles('build/listProductsReleases.txt') }}

      - name: Run Plugin Verification tasks
        run: ./gradlew runPluginVerifier -Dplugin.verifier.home.dir=${{ steps.properties.outputs.pluginVerifierHomeDir }}

      - name: Collect Plugin Verifier Result
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: pluginVerifier-result
          path: ${{ github.workspace }}/build/reports/pluginVerifier
